{% set data = load_setup_py_data() %}


package:
  name: lineplot-r
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True


requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - r-dplyr
    - r-shiny
    - r-plotly
    - r-plyr
    - r-rcolorbrewer
    - r-shinybs
    - r-shinyjs

test:
  imports:
    - lineplot

about:
  home: {{ data.url }}
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

  summary: {{ data.description }}
  description: {{ data.long_description }}
  doc_url: http://docs.3steps.cn
  dev_url: {{ data.url }}