# {% set data = load_setup_py_data() %}
{% set version = '0.1.0' %}
{% set url = 'https://choppy.3steps.cn/go-choppy/line-plot-r-plugin/' %}
{% set description = 'An choppy plugin to draw an interactive line plot.' %}
{% set long_description = 'The line plot plugin will draw an interactive line plot by using ggplot2 library.' %}

package:
  name: line-plot-r-plugin
  version: {{ version }}


source:
  - path: ../


build:
  include_recipe: True
  entry_points:
    - line-plot-r = line_plot.line_plot:LinePlotRPlugin


requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - mk-media-extension>=0.1.0
    - r-dplyr
    - r-shiny
    - r-plotly
    - r-plyr
    - r-rcolorbrewer
    - r-shinybs
    - r-shinyjs

# test:
#   imports:
#     - line_plot

about:
  home: {{ url }}
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD

  summary: {{ description }}
  description: {{ long_description }}
  doc_url: http://docs.3steps.cn
  dev_url: {{ url }}